#!/bin/bash
DEFAULT_BUILD_CONFIGURATION="debug"

usage() 
{
    echo "usage: utils/integration-test [OPTION...]
  -c, --configuration       swift build configuration mode, default '$DEFAULT_BUILD_CONFIGURATION'"
}

error()
{
    echo $1 
    exit 1
}

check()
{
    message=$1
    shift 
    echo $@
    "$@" || error "$message"
}

build_configuration=$DEFAULT_BUILD_CONFIGURATION

while [ "$1" != "" ] ; do
    case $1 in 
    -c | --configuration ) 
        shift
        build_configuration=$1
        ;;
    * )
        usage 
        exit 1
    esac 
    shift 
done 

check   "error: swift build failed" \
        swift build -c $build_configuration --product integration-test 

binaries=".build/$build_configuration"
if ! [ -f $binaries/integration-test ]; then
    error "error: missing integration-test tool"
fi

check   "error: test failures" \
        $binaries/integration-test 
