#!/bin/bash
DEFAULT_BUILD_CONFIGURATION="debug"
TOOL_NAME="integration-test"

usage() 
{
    echo "usage: utils/$TOOL_NAME [OPTION...]
  -c, --configuration       swift build configuration mode, default '$DEFAULT_BUILD_CONFIGURATION'"
}

error()
{
    echo $1 
    exit 1
}

check()
{
    message=$1
    shift 
    echo $@
    "$@" || error "$message"
}

build_configuration=$DEFAULT_BUILD_CONFIGURATION

while [ "$1" != "" ] ; do
    case $1 in 
    -c | --configuration ) 
        shift
        build_configuration=$1
        ;;
    * )
        usage 
        exit 1
    esac 
    shift 
done 

check   "error: swift build failed" \
        swift build -c $build_configuration --product $TOOL_NAME

binaries=".build/$build_configuration"
if ! [ -f $binaries/$TOOL_NAME ]; then
    error "error: missing $TOOL_NAME tool"
fi

check   "error: test failures" \
        $binaries/$TOOL_NAME

data=(tests/integration/decode/*.jpg)
for file in ${data[@]} ; do 
    size=$(identify -format "%wx%h" jpg:$file)
    convert -depth 8 -size $size "rgb:$file.rgb" "png:$file.rgb.png"
    convert -depth 8 -size $size -define jpeg:dct-method=float "jpeg:$file" rgb:- |\
    convert -depth 8 -size $size rgb:- "png:$file.png"
done 
